### ISSUE TITLE
Html motd?

### ISSUE THREAD

**Issue by Pomdre** [GoneToneStudio/PHP-Minecraft-Query-API#2]
Html motd? :D

**Comment by GoneTone** [comment]
I don't understand what you mean.

**Comment by Pomdre** [comment]
![image](https://user-images.githubusercontent.com/30056774/43769321-c1e905a0-9a39-11e8-9f14-32a72e5fb33a.png)
As this.

**Comment by GoneTone** [comment]
Already added motd html!
