### ISSUE TITLE
Motd extra?

### ISSUE THREAD

**Issue by Pomdre** [GoneToneStudio/PHP-Minecraft-Query-API#3]
Why is this extra stuff coming?
![image](https://user-images.githubusercontent.com/30056774/43845976-85198ac4-9b2d-11e8-8cff-b4c90eea125d.png)

[http://mc-status-api.gearhostpreview.com/json.php?host=90.149.222.18&port=25565](url)

Raw json:
`{
    "status": "Online",
    "motd": {
        "ingame": {
            "extra": [
                {
                    "color": "yellow",
                    "bold": true,
                    "text": "Dag"
                },
                {
                    "color": "yellow",
                    "bold": true,
                    "text": " "
                },
                {
                    "color": "green",
                    "bold": true,
                    "text": "& "
                },
                {
                    "color": "blue",
                    "bold": true,
                    "text": "Natt"
                },
                {
                    "color": "white",
                    "text": "                                                     En offisiell server for "
                },
                {
                    "color": "dark_green",
                    "text": "Level Up Community"
                },
                {
                    "color": "white",
                    "text": "."
                }
            ],
            "text": ""
        },
        "clean": {
            "extra": [
                {
                    "color": "yellow",
                    "bold": true,
                    "text": "Dag"
                },
                {
                    "color": "yellow",
                    "bold": true,
                    "text": " "
                },
                {
                    "color": "green",
                    "bold": true,
                    "text": "& "
                },
                {
                    "color": "blue",
                    "bold": true,
                    "text": "Natt"
                },
                {
                    "color": "white",
                    "text": "                                                     En offisiell server for "
                },
                {
                    "color": "dark_green",
                    "text": "Level Up Community"
                },
                {
                    "color": "white",
                    "text": "."
                }
            ],
            "text": ""
        },
        "html": {
            "extra": [
                {
                    "color": "yellow",
                    "bold": true,
                    "text": "Dag"
                },
                {
                    "color": "yellow",
                    "bold": true,
                    "text": " "
                },
                {
                    "color": "green",
                    "bold": true,
                    "text": "& "
                },
                {
                    "color": "blue",
                    "bold": true,
                    "text": "Natt"
                },
                {
                    "color": "white",
                    "text": "                                                     En offisiell server for "
                },
                {
                    "color": "dark_green",
                    "text": "Level Up Community"
                },
                {
                    "color": "white",
                    "text": "."
                }
            ],
            "text": ""
        }
    },
    "host": {
        "host": "90.149.222.18",
        "port": "25565"
    },
    "players": {
        "max": 250,
        "online": 3
    },
    "version": {
        "version": "1.8.x-1.13.x",
        "protocol": 393
    },
    "queryinfo": {
        "agreement": "Ping",
        "processed": "0.5063"
    }
}`

**Comment by GoneTone** [comment]
The MOTD returned by the server is the json format.

**Comment by Pomdre** [comment]
But how can I get it and look like this? 
![image](https://user-images.githubusercontent.com/30056774/43852585-e2b158e6-9b3d-11e8-853d-0a71df5b51d3.png)

**Comment by GoneTone** [comment]
Use plugin

**Comment by Pomdre** [comment]
Then I can not use that in my program

**Comment by GoneTone** [comment]
What do you mean?

**Comment by Pomdre** [comment]
I am createing a server list website

**Comment by Pomdre** [comment]
and I need clean motd without extra

**Comment by GoneTone** [comment]
Those MOTDs are returned by the server. If it is in json format, you may have to write your own judgment and then connect the strings together.
