### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ghost** [GoneToneStudio/PHP-Minecraft-Query-API#4]
http://1x.x.x.x/json.php?host=sg.lbsg.net&port=19132 is just bringing up json.php

**Comment by GoneTone** [comment]
??

**Comment by ghost** [comment]
Moved the files to my website's and when i try to do what i commented above it just opens the .json file

**Comment by GoneTone** [comment]
This is the project that outputs json...


For webpage usage, please refer to https://github.com/GoneTone/webpage-minecraft-server-status

**Comment by ghost** [comment]
U got English tutorial?

**Comment by GoneTone** [comment]
no, sorry.

**Comment by ghost** [comment]
Ok
